version: '3.4'

services:
  fmf:
    image: missingno/fmf
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000 --noreload
    restart: always
